### ISSUE TITLE
Different output when running script as Nagios user

### ISSUE THREAD

**Issue by NMerch** [cafuego/check_puppetmaster#5]
I get a different output when running the script as nagios user than I do when root.  When running as nagios the output is alway '0 ok'.

Nagios user has read access to all of the YAML files.

[root@puppet-master tmp]# check_puppetmaster/check_puppetmaster 
CRITICAL: 1 critical (wiki-test.domain.com); 1 warning (synergy-node-1.domain.com); 9 ok.
[root@puppet-master tmp]# 
[root@puppet-master tmp]# su nagios
bash-4.1$ check_puppetmaster/check_puppetmaster 
OK: 0 ok.bash-4.1$ 

Any ideas?

**Comment by cafuego** [comment]
Odd... are all the shell utils I use in the $PATH for the nagios user?

You could add 'set -x' to the top of the script, that'll make it output everything it does as debug.

**Comment by NMerch** [comment]
Thanks for the response.

As far as I can tell all of the utils are in the path.

The problem is the command to get the list of puppet cert is not returning anything.

As the Nagios user when I run:

```
bash-4.1$/usr/bin/puppet cert -la 
bash-4.1$
```

When I run the same command as root I get the list of certs as one would expect.  

I'm not sure why the command is failing, I would expect an error if it were a permsissions issue.  Nagios user can execute /user/bin/puppet help without issue (just a random command I picked to test.

```
bash-4.1$ ls -la /usr/bin/puppet 
-rwxr-xr-x. 1 root root 90 Apr 15 23:08 /usr/bin/puppet
bash-4.1$ 
```

Output of script with set -x enabled.
- YAMLPATH=/var/lib/puppet/yaml/node
- STATUS_OK=0
- STATUS_WARNING=1
- STATUS_CRITICAL=2
- STATUS_UNKNOWN=3
- INTERVAL_WARNING=7200
- INTERVAL_CRITICAL=86400
- PUPPET=/usr/bin/puppet
- COMMAND=cert
- PARAMS=-la
- PERFDATA=no
- IGNORE_HOSTS=
- '[' -f /etc/default/check_puppetmaster ']'
- '[' '!' -r /var/lib/puppet/yaml/node ']'
- status=OK
- ret=0
- i_count=0
- o_count=0
- w_count=0
- w_string=
- e_count=0
- e_string=
- p_string=
  ++ date +%s
- NOW=1399906641
  ++ awk '/^+/ {print $2}'
  ++ tr -d '"'
  ++ /usr/bin/puppet cert -la
- '[' -n '' ']'
- '[' -n '' ']'
- '[' 0 -gt 0 ']'
- s_string=' 0 ok.'
- '[' 0 -gt 0 ']'
- '[' 0 -gt 0 ']'
- '[' no = yes ']'
- echo -n 'OK: 0 ok.'
  OK: 0 ok.+ exit 0

**Comment by cafuego** [comment]
Aha! puppet cert is special though, to keep the certificates safe from prying eyes.

On my server, the certs are in /var/lib/puppet/ssl/ca/signed, which is owned by puppet:puppet with user and group access only. If yours is the same, you can add the nagios user to the puppet group, to give it read access on the certificates, and it’ll be all happy then.

Cheers,
- Peter.

**Comment by NMerch** [comment]
Got it working, thanks for the assistance and the plugin!
